version: '3'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simplerest
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser
      TZ: 'Asia/Tokyo'
    command: mysqld --port=3300 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/:/etc/mysql/conf.d/
    ports:
      - 3300:3300
  go:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 9010:9010
    depends_on:
      - "db"

volumes:
  db-data:
    driver: local